### ISSUE TITLE
라이선스 관련 문의

### ISSUE THREAD

**Issue by LiteHell** [gdl-888/banana#11]
안녕하세요, [js-namumark](https://github.com/LiteHell/js-namumark) 개발자 LiteHell입니다. 귀하의 번영을 기원합니다.
[banana](https://github.com/gdl-blue/banana) 프로그램에서 js-namumark 라이브러리를 이용한 사실을 확인했습니다.
해당 라이브러리는 AGPL-3.0 라이선스를 채택한 라이브러리이기 때문에, AGPL-3.0의 조문에 따라 해당 라이브러리를 이용한 프로그램들 또한 AGPL-3.0을 라이브러리를 채택해야 합니다.

커밋 6e824dfc28f5a7c4539e417da79522cf6b7f4f61 에서는 AGPL-3.0을 채택하셨다가 커밋 594e0b154464610b32fc22ff20eac89956ed8f76 에서 라이선스를 변경하신 거로 보아 해당 사항 알고 계신 부분으로 이해가 되는데, 어찌됐든 해당 사항 검토하여 라이선스를 AGPL-3.0으로 변경해주시면 감사하겠습니다.

**Comment by gdl-blue** [comment]
https://github.com/gdl-blue/banana/commit/dc804ab29acf14b8179ea5e0772dcd81308e19fe

**Comment by LiteHell** [comment]
AGPL 적용시 AGPL 라이선스 사본을 같이 제공해야 합니다. 따라서 LICENSE 파일 내용을 [AGPL 라이선스 전문](https://www.gnu.org/licenses/agpl-3.0.txt)으로 변경하셔야 됩니다.

그 외에는 없습니다.

**Comment by gdl-blue** [comment]
https://github.com/gdl-blue/banana/blob/master/LICENSE

**Comment by LiteHell** [comment]
확인했습니다. 좋은 하루 되세요.
